mr2:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  ## LEG CONTROLLERS
  # Leg1 "ontrollers
  fr_leg1_controller:
    type: position_controllers/JointPositionController
    joint: fr_leg1_joint

  fl_leg1_controller:
    type: position_controllers/JointPositionController
    joint: fl_leg1_joint

  rr_leg1_controller:
    type: position_controllers/JointPositionController
    joint: rr_leg1_joint

  rl_leg1_controller:
    type: position_controllers/JointPositionController
    joint: rl_leg1_joint

  # Leg2 "ontrollers
  fr_leg2_controller:
    type: position_controllers/JointPositionController
    joint: fr_leg2_joint

  fl_leg2_controller:
    type: position_controllers/JointPositionController
    joint: fl_leg2_joint

  rr_leg2_controller:
    type: position_controllers/JointPositionController
    joint: rr_leg2_joint

  rl_leg2_controller:
    type: position_controllers/JointPositionController
    joint: rl_leg2_joint

  # Leg3 "ontrollers
  fr_leg3_controller:
    type: position_controllers/JointPositionController
    joint: fr_leg3_joint

  fl_leg3_controller:
    type: position_controllers/JointPositionController
    joint: fl_leg3_joint

  rr_leg3_controller:
    type: position_controllers/JointPositionController
    joint: rr_leg3_joint

  rl_leg3_controller:
    type: position_controllers/JointPositionController
    joint: rl_leg3_joint

  gazebo_ros_control/pid_gains:
    fr_leg1_joint: {p: 10.0, i: 0.0, d: 1.0}
    fr_leg2_joint: {p: 10.0, i: 0.0, d: 1.0}
    fr_leg3_joint: {p: 10.0, i: 0.0, d: 1.0}
    fl_leg1_joint: {p: 10.0, i: 0.0, d: 1.0}
    fl_leg2_joint: {p: 10.0, i: 0.0, d: 1.0}
    fl_leg3_joint: {p: 10.0, i: 0.0, d: 1.0}
    rr_leg1_joint: {p: 10.0, i: 0.0, d: 1.0}
    rr_leg2_joint: {p: 10.0, i: 0.0, d: 1.0}
    rr_leg3_joint: {p: 10.0, i: 0.0, d: 1.0}
    rl_leg1_joint: {p: 10.0, i: 0.0, d: 1.0}
    rl_leg2_joint: {p: 10.0, i: 0.0, d: 1.0}
    rl_leg3_joint: {p: 10.0, i: 0.0, d: 1.0}
