mr2:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  ## LEG CONTROLLERS
  # Leg1 "ontrollers
  fr_leg1_controller:
    type: velocity_controllers/JointPositionController
    joint: fr_leg1_joint
    pid: {p: 80.0, i: 0.01, d: 10.0}

  fl_leg1_controller:
    type: velocity_controllers/JointPositionController
    joint: fl_leg1_joint
    pid: {p: 80.0, i: 0.01, d: 10.0}

  rr_leg1_controller:
    type: velocity_controllers/JointPositionController
    joint: rr_leg1_joint
    pid: {p: 80.0, i: 0.01, d: 10.0}

  rl_leg1_controller:
    type: velocity_controllers/JointPositionController
    joint: rl_leg1_joint
    pid: {p: 80.0, i: 0.01, d: 10.0}

  # Leg2 "ontrollers
  fr_leg2_controller:
    type: velocity_controllers/JointPositionController
    joint: fr_leg2_joint
    pid: {p: 80.0, i: 0.01, d: 10.0}

  fl_leg2_controller:
    type: velocity_controllers/JointPositionController
    joint: fl_leg2_joint
    pid: {p: 80.0, i: 0.01, d: 10.0}

  rr_leg2_controller:
    type: velocity_controllers/JointPositionController
    joint: rr_leg2_joint
    pid: {p: 80.0, i: 0.01, d: 10.0}

  rl_leg2_controller:
    type: velocity_controllers/JointPositionController
    joint: rl_leg2_joint
    pid: {p: 80.0, i: 0.01, d: 10.0}

  # Leg3 "ontrollers
  fr_leg3_controller:
    type: velocity_controllers/JointPositionController
    joint: fr_leg3_joint
    pid: {p: 80.0, i: 0.01, d: 10.0}

  fl_leg3_controller:
    type: velocity_controllers/JointPositionController
    joint: fl_leg3_joint
    pid: {p: 80.0, i: 0.01, d: 10.0}

  rr_leg3_controller:
    type: velocity_controllers/JointPositionController
    joint: rr_leg3_joint
    pid: {p: 80.0, i: 0.01, d: 10.0}

  rl_leg3_controller:
    type: velocity_controllers/JointPositionController
    joint: rl_leg3_joint
    pid: {p: 80.0, i: 0.01, d: 10.0}
